name: checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    uses: cxreiff/github_workflows/.github/workflows/rust_checks.yml@main
    permissions:
      checks: write
    with:
      linux_dependencies: "libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev"
